-- Employee table for storing base salary information
-- Base salary ONLY: no bonuses, equity, allowances
-- Salary stored in employee's native local currency

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    employment_status VARCHAR(30) NOT NULL,
    current_salary DECIMAL(19, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    
    -- Constraints for data integrity
    CONSTRAINT ck_employee_salary_positive CHECK (current_salary > 0),
    CONSTRAINT ck_employee_currency_length CHECK (length(currency) = 3)
);

-- Indexes for query patterns
-- Search by employee number (unique, fastest lookup)
CREATE UNIQUE INDEX idx_employee_employee_number ON employee (employee_number);

-- Filtering by country, department, job title, employment status
CREATE INDEX idx_employee_country ON employee (country);
CREATE INDEX idx_employee_department ON employee (department);
CREATE INDEX idx_employee_job_title ON employee (job_title);
CREATE INDEX idx_employee_employment_status ON employee (employment_status);

-- Name search/sort (supports case-insensitive queries via lower() in app)
CREATE INDEX idx_employee_last_name_first_name ON employee (last_name, first_name);

