CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    employment_status VARCHAR(30) NOT NULL,
    current_salary DECIMAL(19, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    CONSTRAINT uk_employee_employee_number UNIQUE (employee_number)
);

CREATE INDEX idx_employee_country ON employee (country);
CREATE INDEX idx_employee_department ON employee (department);
CREATE INDEX idx_employee_job_title ON employee (job_title);
CREATE INDEX idx_employee_employment_status ON employee (employment_status);
CREATE INDEX idx_employee_last_name_first_name ON employee (last_name, first_name);

