-- FX Rate table for currency conversion to USD
-- Used for analytics reporting currency normalization
-- Rates are static/seeded; not live updated

CREATE TABLE fx_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency CHAR(3) NOT NULL UNIQUE,
    rate_to_usd DECIMAL(10, 6) NOT NULL,
    CONSTRAINT ck_fx_rate_currency_length CHECK (length(currency) = 3),
    CONSTRAINT ck_fx_rate_positive CHECK (rate_to_usd > 0)
);

CREATE UNIQUE INDEX idx_fx_rate_currency ON fx_rate (currency);

-- Insert static FX rates
-- These are representative rates and remain constant for deterministic analytics
INSERT INTO fx_rate (currency, rate_to_usd) VALUES
    ('USD', 1.000000),
    ('INR', 83.000000),
    ('GBP', 1.270000),
    ('EUR', 1.100000),
    ('CAD', 1.360000),
    ('AUD', 1.530000),
    ('SGD', 0.740000),
    ('JPY', 149.000000);

