spring:
  application:
    name: payLens
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_schema: public
  flyway:
    enabled: true
    default-schema: public
    schemas: public
    locations: classpath:db/migration

paylens:
  employee:
    seed:
      enabled: false
